export type ColumnProfile = { null_count: number; null_percentage: number; distinct_count: number; minimum: string | null; maximum: string | null; samples: string[] }
export type ColumnMetadata = { name: string; dtype: string; description: string | null; profile: ColumnProfile | null }
export type DatasetSummary = { id: string; name: string; version: string; schema_hash: string; row_count: number; created_at: string; updated_at: string }
export type TableMetadata = { name: string; description: string | null; row_count: number; columns: ColumnMetadata[] }
export type DatasetSchema = { dataset: DatasetSummary; table: TableMetadata; warnings: string[] }
export type APIError = { error: { code: string; message: string; request_id?: string } }
export type QueryRequest = { dataset_id: string; question: string; conversation_id?: string | null; visualize?: boolean; max_rows?: number }
export type RouterResult = { route: 'analytics_query' | 'schema_question' | 'general_question' | 'follow_up' | 'unsupported'; requires_database: boolean; requires_visualization: boolean; confidence: number }
export type Measure = { field: string; aggregation: string }
export type Filter = { field: string; operator: string; value: string | number | boolean | null }
export type Join = { left_table: string; left_column: string; right_table: string; right_column: string }
export type OrderBy = { field: string; direction: 'ASC' | 'DESC' }
export type PlannerResult = { objective: string; tables_needed: string[]; dimensions: string[]; measures: Measure[]; filters: Filter[]; joins: Join[]; group_by: string[]; order_by: OrderBy[]; limit: number | null; visualization: string | null; assumptions: string[] }
export type RetrievalDocument = { document_id: string; object_type: string; table_name: string; column_name: string | null; score: number; content: string }
export type RetrievalResult = { dataset_id: string; documents: RetrievalDocument[] }
export type GeneratedSQL = { sql: string; referenced_tables: string[]; referenced_columns: string[]; assumptions: string[] }
export type QueryResult = { columns: string[]; rows: unknown[][]; row_count: number; truncated: boolean; duration_ms: number }
export type ValidationResult = { status: 'approved' | 'rejected'; checks: { name: string; passed: boolean }[]; referenced_tables: string[]; referenced_columns: string[]; reasons: { code: string; message: string }[] }
export type Visualization = { type: 'kpi' | 'bar' | 'line' | 'scatter' | 'table'; x: string | null; y: string | null; value: string | null }
export type PipelineStage = { name: string; duration_ms: number }
export type QueryMetadata = { latency_ms: number; stages: PipelineStage[]; cache_hit: boolean; repair_attempts: number }
export type QueryResponse = { query_id: string; status: 'verified' | 'completed' | 'failed' | 'needs_context' | 'unsupported'; route: RouterResult | null; plan: PlannerResult | null; answer: string | null; sql: string | null; validation: ValidationResult | null; result: QueryResult | null; result_profile: unknown | null; visualization: Visualization | null; findings: string[]; assumptions: string[]; evidence: RetrievalResult | null; error: { code: string; message: string } | null; metadata: QueryMetadata }
